// This source file is generated by a tool.
#pragma warning disable CS1591  // CS1591: Missing XML comment for publicly visible type or member

namespace Vrmac.Input.Linux
{
	/// <summary>Bus types of input devices</summary>
	public enum eBusType: byte
	{
		PCI = 0x01,
		ISAPNP = 0x02,
		USB = 0x03,
		HIL = 0x04,
		Bluetooth = 0x05,
		Virtual = 0x06,
		ISA = 0x10,
		I8042 = 0x11,
		XTKBD = 0x12,
		RS232 = 0x13,
		GamePort = 0x14,
		ParallelPort = 0x15,
		Amiga = 0x16,
		ADB = 0x17,
		I2C = 0x18,
		HOST = 0x19,
		GSC = 0x1A,
		Atari = 0x1B,
		SPI = 0x1C,
		RMI = 0x1D,
		CEC = 0x1E,
		Intel = 0x1F,
	}
}