// This source file is generated by a tool.
#pragma warning disable CS1591  // CS1591: Missing XML comment for publicly visible type or member

namespace Vrmac.Input.Linux
{
	/// <summary>LEDs of input devices</summary>
	public enum eLed: byte
	{
		NumLock = 0x00,
		CapsLock = 0x01,
		ScrollLock = 0x02,
		Compose = 0x03,
		Kana = 0x04,
		Sleep = 0x05,
		Suspend = 0x06,
		Mute = 0x07,
		Misc = 0x08,
		Mail = 0x09,
		Charging = 0x0a,
	}
}