// This source file is generated by a tool.
#pragma warning disable CS1591  // CS1591: Missing XML comment for publicly visible type or member

namespace Vrmac.Input.Linux
{
	/// <summary>Miscellaneous events</summary>
	public enum eMiscEvent: byte
	{
		Serial = 0x00,
		Pulseled = 0x01,
		Gesture = 0x02,
		Raw = 0x03,
		Scan = 0x04,
		Timestamp = 0x05,
	}
}