// This C# source file has been generated by a T4 template.
namespace VrmacVideo.Containers.HEVC
{
	/// <summary>Rec. ITU-T H.265 v7 Table 7-1</summary>
	public enum eNaluType: byte
	{
		/// <summary>Coded slice segment of a non-TSA, non-STSA trailing picture</summary>
		TRAIL_N = 0,
		/// <summary>Coded slice segment of a non-TSA, non-STSA trailing picture</summary>
		TRAIL_R = 1,
		/// <summary>Coded slice segment of a TSA picture</summary>
		TSA_N = 2,
		/// <summary>Coded slice segment of a TSA picture</summary>
		TSA_R = 3,
		/// <summary>Coded slice segment of an STSA picture</summary>
		STSA_N = 4,
		/// <summary>Coded slice segment of an STSA picture</summary>
		STSA_R = 5,
		/// <summary>Coded slice segment of a RADL picture</summary>
		RADL_N = 6,
		/// <summary>Coded slice segment of a RADL picture</summary>
		RADL_R = 7,
		/// <summary>Coded slice segment of a RASL picture</summary>
		RASL_N = 8,
		/// <summary>Coded slice segment of a RASL picture</summary>
		RASL_R = 9,
		/// <summary>Reserved non-IRAP SLNR VCL NAL unit type</summary>
		RSV_VCL_N10 = 10,
		/// <summary>Reserved non-IRAP SLNR VCL NAL unit type</summary>
		RSV_VCL_N12 = 12,
		/// <summary>Reserved non-IRAP SLNR VCL NAL unit type</summary>
		RSV_VCL_N14 = 14,
		/// <summary>Reserved non-IRAP sub-layer reference VCL NAL unit type </summary>
		RSV_VCL_R11 = 11,
		/// <summary>Reserved non-IRAP sub-layer reference VCL NAL unit type</summary>
		RSV_VCL_R13 = 13,
		/// <summary>Reserved non-IRAP sub-layer reference VCL NAL unit type</summary>
		RSV_VCL_R15 = 15,
		/// <summary>Coded slice segment of a BLA picture</summary>
		BLA_W_LP = 16,
		/// <summary>Coded slice segment of a BLA picture</summary>
		BLA_W_RADL = 17,
		/// <summary>Coded slice segment of a BLA picture</summary>
		BLA_N_LP = 18,
		/// <summary>Coded slice segment of an IDR picture</summary>
		IDR_W_RADL = 19,
		/// <summary>Coded slice segment of an IDR picture</summary>
		IDR_N_LP = 20,
		/// <summary>Coded slice segment of a CRA picture</summary>
		CRA_NUT = 21,
		/// <summary>Reserved IRAP VCL NAL unit type</summary>
		RSV_IRAP_VCL22 = 22,
		/// <summary>Reserved IRAP VCL NAL unit type</summary>
		RSV_IRAP_VCL23 = 23,
		/// <summary>Video parameter set</summary>
		VPS = 32,
		/// <summary>Sequence parameter set</summary>
		SPS = 33,
		/// <summary>Picture parameter set</summary>
		PPS = 34,
		/// <summary>Access unit delimiter</summary>
		AUD = 35,
		/// <summary>End of sequence</summary>
		EOS = 36,
		/// <summary>End of bitstream</summary>
		EOB = 37,
		/// <summary>Filler data</summary>
		FD = 38,
		/// <summary>Supplemental enhancement information</summary>
		PREFIX_SEI_NUT = 39,
		/// <summary>Supplemental enhancement information</summary>
		SUFFIX_SEI_NUT = 40,
	}
}