// This source file is generated by a T4 template
Texture2D<float> lumaTexture;
Texture2D<float2> chromaTexture;

float4 main( float4 pos: SV_Position ) : SV_Target
{
	int2 locLuma = ( int2 )pos.xy;
	int2 locChroma = locLuma >> 1;

	float luma = lumaTexture.Load( locLuma );
	float2 chroma = chromaTexture.Load( locChroma );
	// float scaledLuma = luma * 1;
	float scaledLuma = luma;
	float4 result;
	result.r = scaledLuma + chroma.y * 1.28033 - 0.640165;
	result.g = scaledLuma - chroma.x * 0.21482 - chroma.y * 0.38059 + 0.297705;
	result.b = scaledLuma + chroma.x * 2.12798 - 1.06399;
	result.a = 1.0;
	return result;
}