// This C# source file has been generated by a T4 template.

namespace VrmacVideo.Containers.MP4
{
	/// <summary>The values are from the spec. Specifically, they are from ISO/IEC 14496-12 spec.</summary>
	public enum eBoxType: uint
	{
		/// <summary>Empty state of the reader; also returned from <see cref="Mp4Reader.readBox" /> when end of file reached.</summary>
		Empty = uint.MaxValue,
		/// <summary>Fake box type returned from <see cref="Mp4Reader.readBox" /> when end of container reached, after it pops the container from the stack.</summary>
		ChildContainerEnd = uint.MaxValue - 1,
		/// <summary>User extension, the actual box type is a GUID as opposed to 4 bytes. Vrmac Video silently skips such boxes.</summary>
		uuid = 0x64697575,

		/// <summary>File type and compatibility, 4.3</summary>
		ftyp = 0x70797466,
		/// <summary>Progressive download information, 8.1.3</summary>
		pdin = 0x6e696470,
		/// <summary>Container for all the metadata, 8.2.1</summary>
		moov = 0x766f6f6d,
		/// <summary>Movie header, overall declarations, 8.2.2</summary>
		mvhd = 0x6468766d,
		/// <summary>Metadata, 8.11.1</summary>
		meta = 0x6174656d,
		/// <summary>Container for an individual track or stream, 8.3.1</summary>
		trak = 0x6b617274,
		/// <summary>Track header, overall information about the track, 8.3.2</summary>
		tkhd = 0x64686b74,
		/// <summary>Track reference container, 8.3.3</summary>
		tref = 0x66657274,
		/// <summary>Track grouping indication, 8.3.4</summary>
		trgr = 0x72677274,
		/// <summary>Edit list container, 8.6.4</summary>
		edts = 0x73746465,
		/// <summary>An edit list, 8.6.6</summary>
		elst = 0x74736c65,
		/// <summary>Container for the media information in a track, 8.4</summary>
		mdia = 0x6169646d,
		/// <summary>Media header, overall information about the media, 8.4.2</summary>
		mdhd = 0x6468646d,
		/// <summary>Handler, declares the media (handler) type, 8.4.3</summary>
		hdlr = 0x726c6468,
		/// <summary>Extended language tag, 8.4.6</summary>
		elng = 0x676e6c65,
		/// <summary>Media information container, 8.4.4</summary>
		minf = 0x666e696d,
		/// <summary>Video media header, overall information (video track only), 12.1.2</summary>
		vmhd = 0x64686d76,
		/// <summary>Sound media header, overall information (sound track only), 12.2.2</summary>
		smhd = 0x64686d73,
		/// <summary>Hint media header, overall information (hint track only), 12.4.2</summary>
		hmhd = 0x64686d68,
		/// <summary>Subtitle media header, overall information (subtitle track only), 12.6.2</summary>
		sthd = 0x64687473,
		/// <summary>Null media header, overall information (some tracks only), 8.4.5.2</summary>
		nmhd = 0x64686d6e,
		/// <summary>Data information box, container metadata, 8.7.1</summary>
		dinf = 0x666e6964,
		/// <summary>Track fragment, 8.8.6</summary>
		traf = 0x66617274,
		/// <summary>Track fragment header, 8.8.7</summary>
		tfhd = 0x64686674,
		/// <summary>Track fragment run, 8.8.8</summary>
		trun = 0x6e757274,
		/// <summary>Sample-To-Group, 8.9.2</summary>
		sbgp = 0x70676273,
		/// <summary>Sample group description, 8.9.3</summary>
		sgpd = 0x64706773,
		/// <summary>Sub-Sample information, 8.7.7</summary>
		subs = 0x73627573,
		/// <summary>Sample auxiliary information sizes, 8.7.8</summary>
		saiz = 0x7a696173,
		/// <summary>Sample auxiliary information offsets, 8.7.9</summary>
		saio = 0x6f696173,
		/// <summary>Track fragment decode time, 8.8.12</summary>
		tfdt = 0x74646674,
		/// <summary>Movie fragment random access, 8.8.9</summary>
		mfra = 0x6172666d,
		/// <summary>Track fragment random access, 8.8.10</summary>
		tfra = 0x61726674,
		/// <summary>Movie fragment random access offset, 8.8.11</summary>
		mfro = 0x6f72666d,
		/// <summary>Media data container, 8.2.2</summary>
		mdat = 0x7461646d,
		/// <summary>Free space, 8.1.2</summary>
		free = 0x65657266,
		/// <summary>Free space, 8.1.2</summary>
		skip = 0x70696b73,
		/// <summary>User-Data, 8.10.1</summary>
		udta = 0x61746475,
		/// <summary>Copyright etc., 8.10.2</summary>
		cprt = 0x74727063,
		/// <summary>Track selection box, 8.10.3</summary>
		tsel = 0x6c657374,
		/// <summary>Sub track box, 8.14.3</summary>
		strk = 0x6b727473,
		/// <summary>Sub track information box, 8.14.4</summary>
		stri = 0x69727473,
		/// <summary>Sub track definition box, 8.14.5</summary>
		strd = 0x64727473,
		/// <summary>Data reference box, declares source(s) of metadata items, 8.7.2</summary>
		dref = 0x66657264,
		/// <summary>Sample table box, container for the time/space map, 8.5.1</summary>
		stbl = 0x6c627473,
		/// <summary>Sample descriptions (codec types, initialization etc.), 8.5.2</summary>
		stsd = 0x64737473,
		/// <summary>(Decoding) time-to-sample, 8.6.1.2</summary>
		stts = 0x73747473,
		/// <summary>(Composition) time to sample, 8.6.1.3</summary>
		ctts = 0x73747463,
		/// <summary>Composition to decode timeline mapping, 8.6.1.4</summary>
		cslg = 0x676c7363,
		/// <summary>Sample-To-Chunk, partial data-offset information, 8.7.4</summary>
		stsc = 0x63737473,
		/// <summary>Sample sizes (framing), 8.7.3.2</summary>
		stsz = 0x7a737473,
		/// <summary>Compact sample sizes (framing), 8.7.3.3</summary>
		stz2 = 0x327a7473,
		/// <summary>Chunk offset, partial data-offset information, 8.7.5</summary>
		stco = 0x6f637473,
		/// <summary>64-bit chunk offset, 8.7.5</summary>
		co64 = 0x34366f63,
		/// <summary>Sync sample table, 8.6.2</summary>
		stss = 0x73737473,
		/// <summary>Shadow sync sample table, 8.6.3</summary>
		stsh = 0x68737473,
		/// <summary>Sample padding bits, 8.7.6</summary>
		padb = 0x62646170,
		/// <summary>Sample degradation priority, 8.7.6</summary>
		stdp = 0x70647473,
		/// <summary>Independent and disposable samples, 8.6.4</summary>
		sdtp = 0x70746473,
		/// <summary>Movie extends box, 8.8.1</summary>
		mvex = 0x7865766d,
		/// <summary>Movie extends header box, 8.8.2</summary>
		mehd = 0x6468656d,
		/// <summary>Track extends defaults, 8.8.3</summary>
		trex = 0x78657274,
		/// <summary>Level assignment, 8.8.13</summary>
		leva = 0x6176656c,
		/// <summary>Movie fragment, 8.8.4</summary>
		moof = 0x666f6f6d,
		/// <summary>Movie fragment header, 8.8.5</summary>
		mfhd = 0x6468666d,
		/// <summary>Item location, 8.11.3</summary>
		iloc = 0x636f6c69,
		/// <summary>Item protection, 8.11.5</summary>
		ipro = 0x6f727069,
		/// <summary>Protection scheme information box, 8.12.1</summary>
		sinf = 0x666e6973,
		/// <summary>Original format box, 8.12.2</summary>
		frma = 0x616d7266,
		/// <summary>Scheme type box, 8.12.5</summary>
		schm = 0x6d686373,
		/// <summary>Scheme information box, 8.12.6</summary>
		schi = 0x69686373,
		/// <summary>Item information, 8.11.6</summary>
		iinf = 0x666e6969,
		/// <summary>XML container, 8.11.2</summary>
		xml = 0x6c6d78,
		/// <summary>Binary XML container, 8.11.2</summary>
		bxml = 0x6c6d7862,
		/// <summary>Primary item reference, 8.11.4</summary>
		pitm = 0x6d746970,
		/// <summary>File delivery item information, 8.13.2</summary>
		fiin = 0x6e696966,
		/// <summary>Partition entry, 8.13.2</summary>
		paen = 0x6e656170,
		/// <summary>File reservoir, 8.13.7</summary>
		fire = 0x65726966,
		/// <summary>File partition, 8.13.3</summary>
		fpar = 0x72617066,
		/// <summary>FEC reservoir, 8.13.4</summary>
		fecr = 0x72636566,
		/// <summary>File delivery session group, 8.13.5</summary>
		segr = 0x72676573,
		/// <summary>Group id to name, 8.13.6</summary>
		gitn = 0x6e746967,
		/// <summary>Item data, 8.11.11</summary>
		idat = 0x74616469,
		/// <summary>Item reference, 8.11.12</summary>
		iref = 0x66657269,
		/// <summary>Additional metadata container, 8.11.7</summary>
		meco = 0x6f63656d,
		/// <summary>Metabox relation, 8.11.8</summary>
		mere = 0x6572656d,
		/// <summary>Segment type, 8.16.2</summary>
		styp = 0x70797473,
		/// <summary>Segment index, 8.16.3</summary>
		sidx = 0x78646973,
		/// <summary>Subsegment index, 8.16.4</summary>
		ssix = 0x78697373,
		/// <summary>Producer reference time, 8.16.5</summary>
		prft = 0x74667270,
	}

	/// <summary>MP4 / QuickTime 'ftyp' designations</summary>
	public enum eFileType: uint
	{
		/// <summary>MP4 Base Media v1 [IS0 14496-12:2003]</summary>
		isom = 0x6d6f7369,
		/// <summary>MP4 Base Media v2 [ISO 14496-12:2005]</summary>
		iso2 = 0x326f7369,
		/// <summary>MP4 Base with AVC extension [ISO 14496-12:2005]</summary>
		avc1 = 0x31637661,
	}

	/// <summary>Media handlers constants</summary>
	public enum eMediaHandler: uint
	{
		/// <summary>Video track</summary>
		vide = 0x65646976,
		/// <summary>Auxiliary video track</summary>
		auxv = 0x76787561,
		/// <summary>Audio track</summary>
		soun = 0x6e756f73,
		/// <summary>Timed metadata</summary>
		meta = 0x6174656d,
		/// <summary>Hint</summary>
		hint = 0x746e6968,
		/// <summary>Text</summary>
		text = 0x74786574,
		/// <summary>Subtitle track</summary>
		subt = 0x74627573,
		/// <summary>Font</summary>
		fdsm = 0x6d736466,
	}

	/// <summary>AVC1 boxes, documented in these proprietary ISO/IEC standards</summary>
	/// <remarks>The standards aren’t free, the committee sells them. Fortunately, some awesome people from both industry and academia uploaded them to the Internets for public access.</remarks>
	public enum eAVC1BoxType: uint
	{
		/// <summary>AVCConfigurationBox</summary>
		avcC = 0x43637661,
		/// <summary>AVCSampleEntry</summary>
		avc1 = 0x31637661,
		/// <summary>AVC2SampleEntry</summary>
		avc2 = 0x32637661,
		/// <summary>MPEG4BitRateBox</summary>
		btrt = 0x74727462,
		/// <summary>MPEG4ExtensionDescriptorsBox</summary>
		m4ds = 0x7364346d,
	}

	public enum eAudioBoxType: uint
	{
		/// <summary>MPEG-4 Audio</summary>
		mp4a = 0x6134706d,
		/// <summary>MPEG-4 Elementary Stream Descriptor</summary>
		esds = 0x73647365,
		/// <summary>Dolby Digital, also known as Dolby AC-3</summary>
		ac3 = 0x332d6361,
	}
}