// This source file is generated by a tool.
#pragma warning disable CS1591  // CS1591: Missing XML comment for publicly visible type or member

namespace Vrmac.Input
{
	/// <summary>Keys of input devices, most often the keyboard ones.</summary>
	/// <remarks>The data is from "linux/input-event-codes.h".
	/// In windowed mode, both Windows and X11 versions translate their codes into this enum on the C++ side of the interop.</remarks>
	public enum eKey: ushort
	{
		Esc = 1,
		D1 = 2,
		D2 = 3,
		D3 = 4,
		D4 = 5,
		D5 = 6,
		D6 = 7,
		D7 = 8,
		D8 = 9,
		D9 = 10,
		D0 = 11,
		Minus = 12,
		Equal = 13,
		Backspace = 14,
		Tab = 15,
		Q = 16,
		W = 17,
		E = 18,
		R = 19,
		T = 20,
		Y = 21,
		U = 22,
		I = 23,
		O = 24,
		P = 25,
		LeftBrace = 26,
		RightBrace = 27,
		Enter = 28,
		LeftCtrl = 29,
		A = 30,
		S = 31,
		D = 32,
		F = 33,
		G = 34,
		H = 35,
		J = 36,
		K = 37,
		L = 38,
		Semicolon = 39,
		Apostrophe = 40,
		Grave = 41,
		LeftShift = 42,
		Backslash = 43,
		Z = 44,
		X = 45,
		C = 46,
		V = 47,
		B = 48,
		N = 49,
		M = 50,
		Comma = 51,
		Dot = 52,
		Slash = 53,
		RightShift = 54,
		Kpasterisk = 55,
		LeftAlt = 56,
		Space = 57,
		CapsLock = 58,
		F1 = 59,
		F2 = 60,
		F3 = 61,
		F4 = 62,
		F5 = 63,
		F6 = 64,
		F7 = 65,
		F8 = 66,
		F9 = 67,
		F10 = 68,
		NumLock = 69,
		ScrollLock = 70,
		Kp7 = 71,
		Kp8 = 72,
		Kp9 = 73,
		Kpminus = 74,
		Kp4 = 75,
		Kp5 = 76,
		Kp6 = 77,
		Kpplus = 78,
		Kp1 = 79,
		Kp2 = 80,
		Kp3 = 81,
		Kp0 = 82,
		Kpdot = 83,
		ZenkakuHankaku = 85,
		/// <summary>The 102-th key found on European keyboards to the right of the Left Shift key.</summary>
		International102nd = 86,
		F11 = 87,
		F12 = 88,
		Ro = 89,
		Katakana = 90,
		Hiragana = 91,
		Henkan = 92,
		KatakanaHiragana = 93,
		Muhenkan = 94,
		Kpjpcomma = 95,
		Kpenter = 96,
		RightCtrl = 97,
		Kpslash = 98,
		Sysrq = 99,
		RightAlt = 100,
		LineFeed = 101,
		Home = 102,
		Up = 103,
		PageUp = 104,
		Left = 105,
		Right = 106,
		End = 107,
		Down = 108,
		PageDown = 109,
		Insert = 110,
		Delete = 111,
		Macro = 112,
		Mute = 113,
		VolumeDown = 114,
		VolumeUp = 115,
		/// <summary>System Control, System Power Down</summary>
		Power = 116,
		Kpequal = 117,
		Kpplusminus = 118,
		Pause = 119,
		/// <summary>Application Launch Button, Compiz Scale (Expose)</summary>
		Scale = 120,
		Kpcomma = 121,
		Hangeul = 122,
		Hanja = 123,
		Yen = 124,
		LeftMeta = 125,
		RightMeta = 126,
		Compose = 127,
		/// <summary>Application Control, Stop</summary>
		Stop = 128,
		Again = 129,
		/// <summary>Application Control, Properties</summary>
		Props = 130,
		/// <summary>Application Control, Undo</summary>
		Undo = 131,
		Front = 132,
		/// <summary>Application Control, Copy</summary>
		Copy = 133,
		/// <summary>Application Control, Open</summary>
		Open = 134,
		/// <summary>Application Control, Paste</summary>
		Paste = 135,
		/// <summary>Application Control, Search</summary>
		Find = 136,
		/// <summary>Application Control, Cut</summary>
		Cut = 137,
		/// <summary>Application Launch Button, Integrated Help Center</summary>
		Help = 138,
		/// <summary>Menu (show menu)</summary>
		Menu = 139,
		/// <summary>Application Launch Button, Calculator</summary>
		Calc = 140,
		Setup = 141,
		/// <summary>System Control, System Sleep</summary>
		Sleep = 142,
		/// <summary>System Wake Up</summary>
		Wakeup = 143,
		/// <summary>Application Launch Button, Local Machine Browser</summary>
		File = 144,
		SendFile = 145,
		DeleteFile = 146,
		Xfer = 147,
		Prog1 = 148,
		Prog2 = 149,
		/// <summary>Application Launch Button, Internet Browser</summary>
		WWW = 150,
		MsDos = 151,
		/// <summary>Application Launch Button, Terminal Lock/Screensaver</summary>
		Coffee = 152,
		/// <summary>Display orientation for e.g. tablets</summary>
		RotateDisplay = 153,
		Cyclewindows = 154,
		Mail = 155,
		/// <summary>Application Control, Bookmarks</summary>
		Bookmarks = 156,
		Computer = 157,
		/// <summary>Application Control, Back</summary>
		Back = 158,
		/// <summary>Application Control, Forward</summary>
		Forward = 159,
		CloseCD = 160,
		EjectCD = 161,
		EjectCloseCD = 162,
		Nextsong = 163,
		Playpause = 164,
		Previoussong = 165,
		StopCD = 166,
		Record = 167,
		Rewind = 168,
		/// <summary>Media Select Telephone</summary>
		Phone = 169,
		Iso = 170,
		/// <summary>Application Launch Button, Consumer Control Configuration</summary>
		Config = 171,
		/// <summary>Application Control, Home</summary>
		Homepage = 172,
		/// <summary>Application Control, Refresh</summary>
		Refresh = 173,
		/// <summary>Application Control, Exit</summary>
		Exit = 174,
		Move = 175,
		Edit = 176,
		ScrollUp = 177,
		ScrollDown = 178,
		Kpleftparen = 179,
		Kprightparen = 180,
		/// <summary>Application Control, New</summary>
		New = 181,
		/// <summary>Application Control, Redo/Repeat</summary>
		Redo = 182,
		F13 = 183,
		F14 = 184,
		F15 = 185,
		F16 = 186,
		F17 = 187,
		F18 = 188,
		F19 = 189,
		F20 = 190,
		F21 = 191,
		F22 = 192,
		F23 = 193,
		F24 = 194,
		PlayCD = 200,
		PauseCD = 201,
		Prog3 = 202,
		Prog4 = 203,
		/// <summary>Application Launch Button, Dashboard</summary>
		Dashboard = 204,
		Suspend = 205,
		/// <summary>Application Control, Close</summary>
		Close = 206,
		Play = 207,
		FastForward = 208,
		BassBoost = 209,
		/// <summary>Application Control, Print</summary>
		Print = 210,
		HP = 211,
		Camera = 212,
		Sound = 213,
		Question = 214,
		EMail = 215,
		Chat = 216,
		Search = 217,
		Connect = 218,
		/// <summary>Application Launch Button, Checkbook/Finance</summary>
		Finance = 219,
		Sport = 220,
		Shop = 221,
		Alterase = 222,
		/// <summary>Application Control, Cancel</summary>
		Cancel = 223,
		BrightnessDown = 224,
		BrightnessUp = 225,
		Media = 226,
		/// <summary>Cycle between available video outputs (Monitor/LCD/TV-out/etc)</summary>
		SwitchVideoMode = 227,
		KbdillumToggle = 228,
		KbdillumDown = 229,
		KbdillumUp = 230,
		/// <summary>Application Control, Send</summary>
		Send = 231,
		/// <summary>Application Control, Reply</summary>
		Reply = 232,
		/// <summary>Application Control, Forward Msg</summary>
		ForwardMail = 233,
		/// <summary>Application Control, Save</summary>
		Save = 234,
		Documents = 235,
		Battery = 236,
		Bluetooth = 237,
		Wlan = 238,
		Uwb = 239,
		Unknown = 240,
		/// <summary>drive next video source</summary>
		VideoNext = 241,
		/// <summary>drive previous video source</summary>
		VideoPrev = 242,
		/// <summary>brightness up, after max is min</summary>
		BrightnessCycle = 243,
		/// <summary>Set Auto Brightness: manual brightness control is off, rely on ambient</summary>
		BrightnessAuto = 244,
		/// <summary>display device to off state</summary>
		DisplayOff = 245,
		/// <summary>Wireless WAN (LTE, UMTS, GSM, etc.)</summary>
		Wwan = 246,
		/// <summary>Key that controls all radios</summary>
		Rfkill = 247,
		/// <summary>Mute / unmute the microphone</summary>
		Micmute = 248,
		Ok = 0x160,
		Select = 0x161,
		Goto = 0x162,
		Clear = 0x163,
		Power2 = 0x164,
		Option = 0x165,
		/// <summary>Application Launch Button, OEM Features/Tips/Tutorial</summary>
		Info = 0x166,
		Time = 0x167,
		Vendor = 0x168,
		Archive = 0x169,
		/// <summary>Media Select Program Guide</summary>
		Program = 0x16a,
		Channel = 0x16b,
		Favorites = 0x16c,
		Epg = 0x16d,
		/// <summary>Media Select Home</summary>
		Pvr = 0x16e,
		Mhp = 0x16f,
		Language = 0x170,
		Title = 0x171,
		Subtitle = 0x172,
		Angle = 0x173,
		Zoom = 0x174,
		Mode = 0x175,
		Keyboard = 0x176,
		Screen = 0x177,
		/// <summary>Media Select Computer</summary>
		Pc = 0x178,
		/// <summary>Media Select TV</summary>
		Tv = 0x179,
		/// <summary>Media Select Cable</summary>
		Tv2 = 0x17a,
		/// <summary>Media Select VCR</summary>
		Vcr = 0x17b,
		/// <summary>VCR Plus</summary>
		Vcr2 = 0x17c,
		/// <summary>Media Select Satellite</summary>
		Sat = 0x17d,
		Sat2 = 0x17e,
		/// <summary>Media Select CD</summary>
		CD = 0x17f,
		/// <summary>Media Select Tape</summary>
		Tape = 0x180,
		Radio = 0x181,
		/// <summary>Media Select Tuner</summary>
		Tuner = 0x182,
		Player = 0x183,
		Text = 0x184,
		/// <summary>Media Select DVD</summary>
		Dvd = 0x185,
		Aux = 0x186,
		Mp3 = 0x187,
		/// <summary>Application Launch Button, Audio Browser</summary>
		Audio = 0x188,
		/// <summary>Application Launch Button, Movie Browser</summary>
		Video = 0x189,
		Directory = 0x18a,
		List = 0x18b,
		/// <summary>Media Select Messages</summary>
		Memo = 0x18c,
		Calendar = 0x18d,
		Red = 0x18e,
		Green = 0x18f,
		Yellow = 0x190,
		Blue = 0x191,
		/// <summary>Channel Increment</summary>
		ChannelUp = 0x192,
		/// <summary>Channel Decrement</summary>
		ChannelDown = 0x193,
		First = 0x194,
		/// <summary>Recall Last</summary>
		Last = 0x195,
		Ab = 0x196,
		Next = 0x197,
		Restart = 0x198,
		Slow = 0x199,
		Shuffle = 0x19a,
		Break = 0x19b,
		Previous = 0x19c,
		Digits = 0x19d,
		Teen = 0x19e,
		Twen = 0x19f,
		/// <summary>Media Select Video Phone</summary>
		Videophone = 0x1a0,
		/// <summary>Media Select Games</summary>
		Games = 0x1a1,
		/// <summary>Application Control, Zoom In</summary>
		Zoomin = 0x1a2,
		/// <summary>Application Control, Zoom Out</summary>
		Zoomout = 0x1a3,
		/// <summary>Application Control, Zoom</summary>
		Zoomreset = 0x1a4,
		/// <summary>Application Launch Button, Word Processor</summary>
		Wordprocessor = 0x1a5,
		/// <summary>Application Launch Button, Text Editor</summary>
		Editor = 0x1a6,
		/// <summary>Application Launch Button, Spreadsheet</summary>
		Spreadsheet = 0x1a7,
		/// <summary>Application Launch Button, Graphics Editor</summary>
		GraphicsEditor = 0x1a8,
		/// <summary>Application Launch Button, Presentation App</summary>
		Presentation = 0x1a9,
		/// <summary>Application Launch Button, Database App</summary>
		Database = 0x1aa,
		/// <summary>Application Launch Button, Newsreader</summary>
		News = 0x1ab,
		/// <summary>Application Launch Button, Voicemail</summary>
		VoiceMail = 0x1ac,
		/// <summary>Application Launch Button, Contacts/Address Book</summary>
		Addressbook = 0x1ad,
		/// <summary>Application Launch Button, Instant Messaging</summary>
		Messenger = 0x1ae,
		/// <summary>Turn display (LCD) on and off</summary>
		DisplayToggle = 0x1af,
		/// <summary>Application Launch Button, Spell Check</summary>
		Spellcheck = 0x1b0,
		/// <summary>Application Launch Button, Logoff</summary>
		Logoff = 0x1b1,
		Dollar = 0x1b2,
		Euro = 0x1b3,
		/// <summary>Consumer - transport controls</summary>
		FrameBack = 0x1b4,
		FrameForward = 0x1b5,
		/// <summary>GenDesc - system context menu</summary>
		ContextMenu = 0x1b6,
		/// <summary>Consumer - transport control</summary>
		MediaRepeat = 0x1b7,
		/// <summary>10 channels up (10+)</summary>
		TenChannelsUp = 0x1b8,
		/// <summary>10 channels down (10-)</summary>
		TenChannelsDown = 0x1b9,
		/// <summary>Application Launch Button, Image Browser</summary>
		Images = 0x1ba,
		DelEol = 0x1c0,
		DelEos = 0x1c1,
		InsLine = 0x1c2,
		DelLine = 0x1c3,
		Fn = 0x1d0,
		FnEsc = 0x1d1,
		FnF1 = 0x1d2,
		FnF2 = 0x1d3,
		FnF3 = 0x1d4,
		FnF4 = 0x1d5,
		FnF5 = 0x1d6,
		FnF6 = 0x1d7,
		FnF7 = 0x1d8,
		FnF8 = 0x1d9,
		FnF9 = 0x1da,
		FnF10 = 0x1db,
		FnF11 = 0x1dc,
		FnF12 = 0x1dd,
		Fn1 = 0x1de,
		Fn2 = 0x1df,
		FnD = 0x1e0,
		FnE = 0x1e1,
		FnF = 0x1e2,
		FnS = 0x1e3,
		FnB = 0x1e4,
		BrailleDot1 = 0x1f1,
		BrailleDot2 = 0x1f2,
		BrailleDot3 = 0x1f3,
		BrailleDot4 = 0x1f4,
		BrailleDot5 = 0x1f5,
		BrailleDot6 = 0x1f6,
		BrailleDot7 = 0x1f7,
		BrailleDot8 = 0x1f8,
		BrailleDot9 = 0x1f9,
		BrailleDot10 = 0x1fa,
		/// <summary>used by phones, remote controls,</summary>
		Numeric0 = 0x200,
		/// <summary>and other keypads</summary>
		Numeric1 = 0x201,
		Numeric2 = 0x202,
		Numeric3 = 0x203,
		Numeric4 = 0x204,
		Numeric5 = 0x205,
		Numeric6 = 0x206,
		Numeric7 = 0x207,
		Numeric8 = 0x208,
		Numeric9 = 0x209,
		NumericStar = 0x20a,
		NumericPound = 0x20b,
		/// <summary>Phone key A - HUT Telephony 0xb9</summary>
		NumericA = 0x20c,
		NumericB = 0x20d,
		NumericC = 0x20e,
		NumericD = 0x20f,
		CameraFocus = 0x210,
		/// <summary>WiFi Protected Setup key</summary>
		WpsButton = 0x211,
		/// <summary>Request switch touchpad on or off</summary>
		TouchpadToggle = 0x212,
		TouchpadOn = 0x213,
		TouchpadOff = 0x214,
		CameraZoomin = 0x215,
		CameraZoomout = 0x216,
		CameraUp = 0x217,
		CameraDown = 0x218,
		CameraLeft = 0x219,
		CameraRight = 0x21a,
		AttendantOn = 0x21b,
		AttendantOff = 0x21c,
		/// <summary>Attendant call on or off</summary>
		AttendantToggle = 0x21d,
		/// <summary>Reading light on or off</summary>
		LightsToggle = 0x21e,
		/// <summary>Ambient light sensor</summary>
		AlsToggle = 0x230,
		/// <summary>Display rotation lock</summary>
		RotateLockToggle = 0x231,
		/// <summary>Application Launch Button, Button Configuration</summary>
		Buttonconfig = 0x240,
		/// <summary>Application Launch Button, Task/Project Manager</summary>
		Taskmanager = 0x241,
		/// <summary>Application Launch Button, Log/Journal/Timecard</summary>
		Journal = 0x242,
		/// <summary>Application Launch Button, Control Panel</summary>
		ControlPanel = 0x243,
		/// <summary>Application Launch Button, Select Task/Application</summary>
		Appselect = 0x244,
		/// <summary>Application Launch Button, Screen Saver</summary>
		Screensaver = 0x245,
		/// <summary>Listening Voice Command</summary>
		VoiceCommand = 0x246,
		/// <summary>Application Launch Button, Context-aware desktop assistant</summary>
		Assistant = 0x247,
		/// <summary>Set Brightness to Minimum</summary>
		BrightnessMin = 0x250,
		/// <summary>Set Brightness to Maximum</summary>
		BrightnessMax = 0x251,
		KeyboardInputAssistPrev = 0x260,
		KeyboardInputAssistNext = 0x261,
		KeyboardInputAssistPrevGroup = 0x262,
		KeyboardInputAssistNextGroup = 0x263,
		KeyboardInputAssistAccept = 0x264,
		KeyboardInputAssistCancel = 0x265,
		RightUp = 0x266,
		RightDown = 0x267,
		LeftUp = 0x268,
		LeftDown = 0x269,
		/// <summary>Show Device's Root Menu</summary>
		RootMenu = 0x26a,
		MediaTopMenu = 0x26b,
		Numeric11 = 0x26c,
		Numeric12 = 0x26d,
		AudioDesc = 0x26e,
		ThreeDimensionalMode = 0x26f,
		NextFavorite = 0x270,
		StopRecord = 0x271,
		PauseRecord = 0x272,
		/// <summary>Video on Demand</summary>
		Vod = 0x273,
		Unmute = 0x274,
		FastReverse = 0x275,
		SlowReverse = 0x276,
		Data = 0x277,
		OnscreenKeyboard = 0x278,
	}
}